using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace project_Euler
{
    public static class euler2
    {
        /*
         * 
         * 
         *  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         * 
         * 
         */
        public static void fib(int max)
        {
            List<int> fibo = new List<int>{1,2};
            int sum = fibo.Last();
            do
            {
                //adds up 2 last numbers
                fibo.Add(fibo.Last() + fibo[fibo.Count - 2]);
                //checks if the last number is even
                if (fibo.Last() % 2 == 0) sum += fibo.Last();

            } while (fibo.Last() < max);
            Console.WriteLine("TOTAL : {0}",sum);
        }
    }
}
